project_name: substreams-sink-kv

release:
  draft: true
  github:
    owner: streamingfast
    name: substreams-sink-kv
  name_template: '{{.Tag}}'
builds:
  - id: substreams-sink-kv
    goos:
    - linux
    - darwin
    goarch:
    - arm64
    - amd64
    targets:
    - linux_amd64
    - darwin_amd64
    - darwin_arm64
    main: ./cmd/substreams-sink-kv
    ldflags: -s -w -X main.version={{.Version}}
    binary: substreams-sink-kv

archives:
  # fireeth
  - name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    id: substreams-sink-kv
    builds:
    - substreams-sink-kv
    replacements:
      amd64: x86_64
      darwin: macOS
      linux: linux
    format: tar.gz
    files:
    - LICENSE
    - README.md
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: dist
signs:
- cmd: keybase
  args:
  - sign
  - --infile
  - $artifact
  - --binary
  - --outfile
  - $signature
  - --detached
  signature: ${artifact}.sig
  artifacts: checksum
env_files:
  github_token: ~/.config/goreleaser/github_token
brews:
  - name: substreams-sink-kv
    ids:
    - substreams-sink-kv
    tap:
      owner: streamingfast
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@streamingfast.io
    homepage: "https://github.com/streamingfast/substreams-sink-kv"
    description: "Substreams Sink tool to extract information to a kv store"
    license: "Apache-2.0"
